---
- hosts: all
  remote_user: root
  roles:
   - motd
   - telegraf
  tasks:
  - name: apt-get update 
    apt: update_cache=yes
  - name: Update dist-upgrade
    apt: upgrade=dist
  - name: install packages
    apt: name={{item}} state=latest
    with_items:
    - htop
    - zsh
    - git
    - nload
    - glances
    - tree
    - tcpdump
    - telegraf
