---
- name: Install - apt-transport-https
  apt:
  name: apt-transport-https
  state: latest
  update_cache: yes
- name: Download Telegraf apt key.
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: present
  become: yes
- name: Add repository telegraf
  apt_repository:
   repo: "deb https://repos.influxdata.com/ubuntu xenial stable"
   state: present
- name: Installation telegraf !!
  apt:
  name: telegraf
  state: latest
- name: Upload conf telegraf inputs
  template:
    src: inputs_system.conf.j2
    dest: /etc/telegraf/telegraf.d/
- name: upload conf telegraf outputs	
  template:
    src: outputs.conf.j2
    dest: /etc/telegraf/telegraf.d/
- name: Restart telegraf
  service: name=telegraf state=restarted